pipeline {
  agent any

  environment {
    GCP_CREDENTIALS = "serviceaccountkey"  
    ZONE = "us-central1-c"
    GIT_CREDENTIALS = "tokenforgcpmiglb" 
    PROJECT_ID = "applied-pager-476808-j5"
  }

  stages {
       stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/TCRDINSEH/gcp-mig-lb.git',
                credentialsId: "${GIT_CREDENTIALS}"
        
            }
        }

    stage('Authenticate to GCP and creating GCP Apache Custom image') {
      steps {
        withCredentials([file(credentialsId: "${GCP_CREDENTIALS}", variable: 'GCP_KEYFILE')]) {
          sh '''
            echo "🔐 Authenticating to GCP..."
            gcloud auth activate-service-account --key-file=$GCP_KEYFILE
            export GOOGLE_APPLICATION_CREDENTIALS=$GCP_KEYFILE
            gcloud config set project ${PROJECT_ID}
            cd packer
            packer init .
            packer build .
            sleep 2
            gcloud compute instance-groups managed rolling-action replace apache-mig-mig --zone=$ZONE --max-surge=1
          '''
        }
      }
    }

  }
  post {
    success {
      echo "✅ Packer successfully created custom Apache image!"
    }
    failure {
      echo "❌ Packer pipeline failed — check logs."
    }
  }
}

